"""Initial migration - all core tables

Revision ID: 001_initial
Revises: 
Create Date: 2026-03-31 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - create all core tables."""
    # This migration will be auto-generated by running:
    # alembic revision --autogenerate -m "Initial migration"
    # 
    # For now, this is a placeholder. Run the command above to generate
    # the actual migration based on your models.
    pass


def downgrade() -> None:
    """Downgrade schema - drop all tables."""
    # This will be auto-generated
    pass
