"""Initial migration - all core tables

Revision ID: 4ce68591e959
Revises: 
Create Date: 2026-03-31 13:38:00.803944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce68591e959'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Handle existing partial schema - drop orphaned types
    conn = op.get_bind()
    for enum in ['genderenum', 'donationtypeenum', 'donationstatusenum', 'voucherstatusenum']:
        try:
            conn.execute(sa.text(f"DROP TYPE IF EXISTS {enum} CASCADE"))
        except Exception:
            pass  # Type cleanup failed or doesn't exist, continue
    
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('nik', sa.String(length=16), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='genderenum'), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_created_at'), 'user_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_is_active'), 'user_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_profiles_nik'), 'user_profiles', ['nik'], unique=True)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_user_entity', 'audit_logs', ['user_id', 'entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_active'), 'audit_logs', ['is_active'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('beneficiary_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_size', sa.Integer(), nullable=True),
    sa.Column('vouchers_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fies_score', sa.Integer(), nullable=True),
    sa.Column('fies_classification', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiary_profiles_created_at'), 'beneficiary_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_beneficiary_profiles_id'), 'beneficiary_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_beneficiary_profiles_is_active'), 'beneficiary_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_beneficiary_profiles_user_id'), 'beneficiary_profiles', ['user_id'], unique=True)
    op.create_table('donor_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_donated', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('children_sponsored', sa.Integer(), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('corporate_name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donor_profiles_created_at'), 'donor_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_donor_profiles_id'), 'donor_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_donor_profiles_is_active'), 'donor_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_donor_profiles_user_id'), 'donor_profiles', ['user_id'], unique=True)
    op.create_table('vendor_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('store_address', sa.Text(), nullable=False),
    sa.Column('store_phone', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_account_holder', sa.String(length=255), nullable=True),
    sa.Column('settlement_status', sa.String(length=50), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_profiles_created_at'), 'vendor_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_vendor_profiles_id'), 'vendor_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_profiles_is_active'), 'vendor_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_vendor_profiles_user_id'), 'vendor_profiles', ['user_id'], unique=True)
    op.create_table('children',
    sa.Column('beneficiary_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='genderenum'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_beneficiary_id'), 'children', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_children_created_at'), 'children', ['created_at'], unique=False)
    op.create_index(op.f('ix_children_id'), 'children', ['id'], unique=False)
    op.create_index(op.f('ix_children_is_active'), 'children', ['is_active'], unique=False)
    op.create_table('donations',
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('type', sa.Enum('one_time', 'subscription', name='donationtypeenum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'refunded', name='donationstatusenum'), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('midtrans_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_config', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donor_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['beneficiary_profiles.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_donation_created_status', 'donations', ['created_at', 'status'], unique=False)
    op.create_index('idx_donation_donor_status', 'donations', ['donor_id', 'status'], unique=False)
    op.create_index(op.f('ix_donations_created_at'), 'donations', ['created_at'], unique=False)
    op.create_index(op.f('ix_donations_donor_id'), 'donations', ['donor_id'], unique=False)
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    op.create_index(op.f('ix_donations_is_active'), 'donations', ['is_active'], unique=False)
    op.create_index(op.f('ix_donations_midtrans_transaction_id'), 'donations', ['midtrans_transaction_id'], unique=True)
    op.create_index(op.f('ix_donations_recipient_id'), 'donations', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_donations_status'), 'donations', ['status'], unique=False)
    op.create_table('fies_surveys',
    sa.Column('beneficiary_id', sa.UUID(), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('survey_date', sa.DateTime(), nullable=False),
    sa.Column('survey_month', sa.Integer(), nullable=False),
    sa.Column('survey_year', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fies_survey_beneficiary_period', 'fies_surveys', ['beneficiary_id', 'survey_year', 'survey_month'], unique=False)
    op.create_index(op.f('ix_fies_surveys_beneficiary_id'), 'fies_surveys', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_fies_surveys_created_at'), 'fies_surveys', ['created_at'], unique=False)
    op.create_index(op.f('ix_fies_surveys_id'), 'fies_surveys', ['id'], unique=False)
    op.create_index(op.f('ix_fies_surveys_is_active'), 'fies_surveys', ['is_active'], unique=False)
    op.create_index(op.f('ix_fies_surveys_survey_date'), 'fies_surveys', ['survey_date'], unique=False)
    op.create_table('orders',
    sa.Column('beneficiary_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('voucher_used', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_paid', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_beneficiary_vendor', 'orders', ['beneficiary_id', 'vendor_id'], unique=False)
    op.create_index('idx_order_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_beneficiary_id'), 'orders', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_is_active'), 'orders', ['is_active'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_vendor_id'), 'orders', ['vendor_id'], unique=False)
    op.create_table('products',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('voucher_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_name_vendor', 'products', ['name', 'vendor_id'], unique=False)
    op.create_index('idx_product_vendor_category', 'products', ['vendor_id', 'category_id'], unique=False)
    op.create_index(op.f('ix_products_approval_status'), 'products', ['approval_status'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_vendor_id'), 'products', ['vendor_id'], unique=False)
    op.create_table('settlements',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_redemptions', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('admin_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payout_date', sa.Date(), nullable=True),
    sa.Column('bank_transfer_reference', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_settlement_vendor_period', 'settlements', ['vendor_id', 'period_start'], unique=False)
    op.create_index(op.f('ix_settlements_created_at'), 'settlements', ['created_at'], unique=False)
    op.create_index(op.f('ix_settlements_id'), 'settlements', ['id'], unique=False)
    op.create_index(op.f('ix_settlements_is_active'), 'settlements', ['is_active'], unique=False)
    op.create_index(op.f('ix_settlements_status'), 'settlements', ['status'], unique=False)
    op.create_index(op.f('ix_settlements_vendor_id'), 'settlements', ['vendor_id'], unique=False)
    op.create_table('nutrition_measurements',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('height', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('muac', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('z_score_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('z_score_height', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('z_score_weight_height', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nutrition_measurement_child_date', 'nutrition_measurements', ['child_id', 'measurement_date'], unique=False)
    op.create_index(op.f('ix_nutrition_measurements_child_id'), 'nutrition_measurements', ['child_id'], unique=False)
    op.create_index(op.f('ix_nutrition_measurements_created_at'), 'nutrition_measurements', ['created_at'], unique=False)
    op.create_index(op.f('ix_nutrition_measurements_id'), 'nutrition_measurements', ['id'], unique=False)
    op.create_index(op.f('ix_nutrition_measurements_is_active'), 'nutrition_measurements', ['is_active'], unique=False)
    op.create_index(op.f('ix_nutrition_measurements_measurement_date'), 'nutrition_measurements', ['measurement_date'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_created_at'), 'order_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_is_active'), 'order_items', ['is_active'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('vouchers',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('beneficiary_id', sa.UUID(), nullable=False),
    sa.Column('donation_id', sa.UUID(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('allocated_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'redeemed', 'expired', 'cancelled', name='voucherstatusenum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_voucher_beneficiary_status', 'vouchers', ['beneficiary_id', 'status'], unique=False)
    op.create_index('idx_voucher_code_status', 'vouchers', ['code', 'status'], unique=False)
    op.create_index(op.f('ix_vouchers_beneficiary_id'), 'vouchers', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_vouchers_code'), 'vouchers', ['code'], unique=True)
    op.create_index(op.f('ix_vouchers_created_at'), 'vouchers', ['created_at'], unique=False)
    op.create_index(op.f('ix_vouchers_donation_id'), 'vouchers', ['donation_id'], unique=False)
    op.create_index(op.f('ix_vouchers_expiry_date'), 'vouchers', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_vouchers_id'), 'vouchers', ['id'], unique=False)
    op.create_index(op.f('ix_vouchers_is_active'), 'vouchers', ['is_active'], unique=False)
    op.create_index(op.f('ix_vouchers_status'), 'vouchers', ['status'], unique=False)
    op.create_table('voucher_redemptions',
    sa.Column('voucher_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_redemptions_created_at'), 'voucher_redemptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_voucher_redemptions_id'), 'voucher_redemptions', ['id'], unique=False)
    op.create_index(op.f('ix_voucher_redemptions_is_active'), 'voucher_redemptions', ['is_active'], unique=False)
    op.create_index(op.f('ix_voucher_redemptions_order_id'), 'voucher_redemptions', ['order_id'], unique=False)
    op.create_index(op.f('ix_voucher_redemptions_voucher_id'), 'voucher_redemptions', ['voucher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voucher_redemptions_voucher_id'), table_name='voucher_redemptions')
    op.drop_index(op.f('ix_voucher_redemptions_order_id'), table_name='voucher_redemptions')
    op.drop_index(op.f('ix_voucher_redemptions_is_active'), table_name='voucher_redemptions')
    op.drop_index(op.f('ix_voucher_redemptions_id'), table_name='voucher_redemptions')
    op.drop_index(op.f('ix_voucher_redemptions_created_at'), table_name='voucher_redemptions')
    op.drop_table('voucher_redemptions')
    op.drop_index(op.f('ix_vouchers_status'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_is_active'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_expiry_date'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_donation_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_created_at'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_code'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_beneficiary_id'), table_name='vouchers')
    op.drop_index('idx_voucher_code_status', table_name='vouchers')
    op.drop_index('idx_voucher_beneficiary_status', table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_is_active'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_created_at'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_nutrition_measurements_measurement_date'), table_name='nutrition_measurements')
    op.drop_index(op.f('ix_nutrition_measurements_is_active'), table_name='nutrition_measurements')
    op.drop_index(op.f('ix_nutrition_measurements_id'), table_name='nutrition_measurements')
    op.drop_index(op.f('ix_nutrition_measurements_created_at'), table_name='nutrition_measurements')
    op.drop_index(op.f('ix_nutrition_measurements_child_id'), table_name='nutrition_measurements')
    op.drop_index('idx_nutrition_measurement_child_date', table_name='nutrition_measurements')
    op.drop_table('nutrition_measurements')
    op.drop_index(op.f('ix_settlements_vendor_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_status'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_is_active'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_created_at'), table_name='settlements')
    op.drop_index('idx_settlement_vendor_period', table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_products_vendor_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_approval_status'), table_name='products')
    op.drop_index('idx_product_vendor_category', table_name='products')
    op.drop_index('idx_product_name_vendor', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_vendor_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_is_active'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_beneficiary_id'), table_name='orders')
    op.drop_index('idx_order_status_created', table_name='orders')
    op.drop_index('idx_order_beneficiary_vendor', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_fies_surveys_survey_date'), table_name='fies_surveys')
    op.drop_index(op.f('ix_fies_surveys_is_active'), table_name='fies_surveys')
    op.drop_index(op.f('ix_fies_surveys_id'), table_name='fies_surveys')
    op.drop_index(op.f('ix_fies_surveys_created_at'), table_name='fies_surveys')
    op.drop_index(op.f('ix_fies_surveys_beneficiary_id'), table_name='fies_surveys')
    op.drop_index('idx_fies_survey_beneficiary_period', table_name='fies_surveys')
    op.drop_table('fies_surveys')
    op.drop_index(op.f('ix_donations_status'), table_name='donations')
    op.drop_index(op.f('ix_donations_recipient_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_midtrans_transaction_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_is_active'), table_name='donations')
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_donor_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_created_at'), table_name='donations')
    op.drop_index('idx_donation_donor_status', table_name='donations')
    op.drop_index('idx_donation_created_status', table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_children_is_active'), table_name='children')
    op.drop_index(op.f('ix_children_id'), table_name='children')
    op.drop_index(op.f('ix_children_created_at'), table_name='children')
    op.drop_index(op.f('ix_children_beneficiary_id'), table_name='children')
    op.drop_table('children')
    op.drop_index(op.f('ix_vendor_profiles_user_id'), table_name='vendor_profiles')
    op.drop_index(op.f('ix_vendor_profiles_is_active'), table_name='vendor_profiles')
    op.drop_index(op.f('ix_vendor_profiles_id'), table_name='vendor_profiles')
    op.drop_index(op.f('ix_vendor_profiles_created_at'), table_name='vendor_profiles')
    op.drop_table('vendor_profiles')
    op.drop_index(op.f('ix_donor_profiles_user_id'), table_name='donor_profiles')
    op.drop_index(op.f('ix_donor_profiles_is_active'), table_name='donor_profiles')
    op.drop_index(op.f('ix_donor_profiles_id'), table_name='donor_profiles')
    op.drop_index(op.f('ix_donor_profiles_created_at'), table_name='donor_profiles')
    op.drop_table('donor_profiles')
    op.drop_index(op.f('ix_beneficiary_profiles_user_id'), table_name='beneficiary_profiles')
    op.drop_index(op.f('ix_beneficiary_profiles_is_active'), table_name='beneficiary_profiles')
    op.drop_index(op.f('ix_beneficiary_profiles_id'), table_name='beneficiary_profiles')
    op.drop_index(op.f('ix_beneficiary_profiles_created_at'), table_name='beneficiary_profiles')
    op.drop_table('beneficiary_profiles')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_active'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('idx_audit_log_user_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_nik'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_is_active'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_created_at'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
